### ISSUE TITLE
Container not reconnecting to server after disconnect

### ISSUE THREAD

**Issue by aburt2** [martabal/immich-exporter#12]
Thank you for this prometheus exporter for Immich just have one issue. 

Whenever the immich-exporter container looses connection to the server for whatever reason (immich container reboots for an update), It doesn't reconnect until I manually restart the container. The only way to notice that it is not working is that I see that one of my targets are down in the Prometheus dashboard. 

Is it possible that the container could either:
1) attempt to reconnect by itself after a disconnection event
2) be marked as unhealthy when it fails to connect to an Immich server

**Comment by martabal** [comment]
Thanks for the report, should be fixed with [v1.3.0](https://github.com/martabal/immich-exporter/releases/tag/v1.3.0) :smile:
