### ISSUE TITLE
5months since last release on Github Docker?

### ISSUE THREAD

**Issue by Allram** [martabal/immich-exporter#8]
Hello,

I have been working with Friendlyfriend4000 on his version of the exporter (https://github.com/friendlyFriend4000/prometheus-immich-exporter), and was going to try yours, but there has been no Github docker build for the last 5 months? So the docker-image has not the latest api changes on Immich v1.85.0 so it tries to get /stats and not /staticstics.

Is it possible for you to run a newer build task?
https://github.com/martabal/immich-exporter/actions/workflows/docker.yml

**Comment by martabal** [comment]
Sorry I completely forgot to run the latest build task. It should be available.

**Comment by martabal** [comment]
I even forgot to change the package visibility :facepalm: https://github.com/martabal/immich-exporter/pkgs/container/immich-exporter
Everything should be fixed.
Thanks for the report
